-- Load Actor data
LOAD DATA LOCAL INFILE './actor1.del' INTO TABLE Actor FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE './actor2.del' INTO TABLE Actor FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE './actor3.del' INTO TABLE Actor FIELDS TERMINATED BY ',';
-- Load Movie data
LOAD DATA LOCAL INFILE './movie.del' INTO TABLE Movie FIELDS TERMINATED BY ',';
-- Load MovieActor data
LOAD DATA LOCAL INFILE './movieactor1.del' INTO TABLE MovieActor FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE './movieactor2.del' INTO TABLE MovieActor FIELDS TERMINATED BY ',';
-- Load MovieGenre data
LOAD DATA LOCAL INFILE './moviegenre.del' INTO TABLE MovieGenre FIELDS TERMINATED BY ',';